#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_3_0 $base.fra49
    set site_3_0 $base.fra63
    set site_3_0 $base.fra64
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5124 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "MLB_gui" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 225 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra38" "Frame_button" vTcl:WidgetProc "MLB_gui" 1
    set site_3_0 $top.fra38
    button $site_3_0.but39 \
        -activebackground {#277ad8} -activeforeground {#000000} \
        -background {#97d8a6} -command recepilist() -compound center \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {List all Recipe} -width 282 
    label $site_3_0.lab83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Number of recepi} 
    vTcl:DefineAlias "$site_3_0.lab83" "Lb_numb" vTcl:WidgetProc "MLB_gui" 1
    text $site_3_0.tex85 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 54 -wrap word 
    .top37.fra38.tex85 configure -font TkTextFont
    .top37.fra38.tex85 insert end text
    vTcl:DefineAlias "$site_3_0.tex85" "Text2" vTcl:WidgetProc "MLB_gui" 1
    place $site_3_0.but39 \
        -in $site_3_0 -x 120 -y 110 -width 200 -relwidth 0 -height 30 \
        -relheight 0 -anchor center -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 20 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tex85 \
        -in $site_3_0 -x 40 -y 40 -width 54 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 45 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 195 
    vTcl:DefineAlias "$top.fra49" "Frame2" vTcl:WidgetProc "MLB_gui" 1
    set site_3_0 $top.fra49
    button $site_3_0.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text save 
    vTcl:DefineAlias "$site_3_0.but50" "button_save" vTcl:WidgetProc "MLB_gui" 1
    button $site_3_0.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text exit 
    vTcl:DefineAlias "$site_3_0.but51" "Button3" vTcl:WidgetProc "MLB_gui" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 10 -y 10 -width 84 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 110 -y 10 -width 69 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra63 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 135 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 575 
    vTcl:DefineAlias "$top.fra63" "Fr_add" vTcl:WidgetProc "MLB_gui" 1
    set site_3_0 $top.fra63
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Add Menu} 
    vTcl:DefineAlias "$site_3_0.lab70" "lb_am" vTcl:WidgetProc "MLB_gui" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Title: 
    vTcl:DefineAlias "$site_3_0.lab71" "Lb_title" vTcl:WidgetProc "MLB_gui" 1
    entry $site_3_0.ent73 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent73" "ent_title" vTcl:WidgetProc "MLB_gui" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Ingredient: 
    vTcl:DefineAlias "$site_3_0.lab74" "lb_ingredient" vTcl:WidgetProc "MLB_gui" 1
    entry $site_3_0.ent75 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent75" "Entry2" vTcl:WidgetProc "MLB_gui" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Instruction: 
    vTcl:DefineAlias "$site_3_0.lab76" "Lb_instruction" vTcl:WidgetProc "MLB_gui" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent77" "Entry3" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad79 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Breackfast -variable {} 
    vTcl:DefineAlias "$site_3_0.rad79" "rb_addbk" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad80 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text lunch -variable {} 
    vTcl:DefineAlias "$site_3_0.rad80" "rb_addllunch" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad81 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Dinner -variable {} 
    vTcl:DefineAlias "$site_3_0.rad81" "rb_adddinner" vTcl:WidgetProc "MLB_gui" 1
    button $site_3_0.but82 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d8d3a8} -command recepilist() \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Add Recepi} 
    vTcl:DefineAlias "$site_3_0.but82" "button_add" vTcl:WidgetProc "MLB_gui" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 10 -y 30 -width 34 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent73 \
        -in $site_3_0 -x 10 -y 50 -width 184 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 10 -y 90 -width 184 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 220 -y 30 -width 63 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 220 -y 50 -width 224 -relwidth 0 -height 80 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad79 \
        -in $site_3_0 -x 470 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.rad80 \
        -in $site_3_0 -x 460 -y 60 -width 82 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad81 \
        -in $site_3_0 -x 460 -y 40 -width 82 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but82 \
        -in $site_3_0 -x 460 -y 90 -width 107 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra64 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 225 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 325 
    vTcl:DefineAlias "$top.fra64" "Frame4" vTcl:WidgetProc "MLB_gui" 1
    set site_3_0 $top.fra64
    listbox $site_3_0.lis65 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 132 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 104 
    .top37.fra64.lis65 configure -font TkFixedFont
    .top37.fra64.lis65 insert end text
    vTcl:DefineAlias "$site_3_0.lis65" "Lb_recipe" vTcl:WidgetProc "MLB_gui" 1
    text $site_3_0.tex66 \
        -background white -font TkTextFont -foreground black -height 204 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 174 -wrap word 
    .top37.fra64.tex66 configure -font TkTextFont
    .top37.fra64.tex66 insert end text
    vTcl:DefineAlias "$site_3_0.tex66" "text_desc" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad67 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text breackfast -variable {} 
    vTcl:DefineAlias "$site_3_0.rad67" "rb_breakfast" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad68 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text lunch -variable {} 
    vTcl:DefineAlias "$site_3_0.rad68" "rb_lunch" vTcl:WidgetProc "MLB_gui" 1
    radiobutton $site_3_0.rad69 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Dinner -variable {} 
    vTcl:DefineAlias "$site_3_0.rad69" "rb_dinner" vTcl:WidgetProc "MLB_gui" 1
    place $site_3_0.lis65 \
        -in $site_3_0 -x 10 -y 80 -width 104 -relwidth 0 -height 132 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex66 \
        -in $site_3_0 -x 140 -y 10 -width 174 -relwidth 0 -height 204 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad67 \
        -in $site_3_0 -x 20 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.rad68 \
        -in $site_3_0 -x 20 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.rad69 \
        -in $site_3_0 -x 20 -y 50 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 10 -y 20 -width 245 -relwidth 0 -height 225 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 380 -y 390 -width 195 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra63 \
        -in $top -x 10 -y 250 -width 575 -relwidth 0 -height 135 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra64 \
        -in $top -x 260 -y 20 -width 325 -relwidth 0 -height 225 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

